### PR TITLE
Start browser or electron after first build

### PR DESCRIPTION
**Pull request by namse**
Some code should be not run.
When I change the code and run `namui start`, it will run previously built code which may not be able to run.

So I changed namui-cli to run browser or electron after first build.

### CODE REVIEW

**Comment by namse** [comment]
Here is new idea, what about start `WasmBundleWebServer` after first build?

If we just make `WasmBundleWebServer` but don't run it, then after first build if we start `WasmBundleWebServer`, it would be better than current PR's solution.

**Comment by bigfoodK** [comment]
Why do you think new idea is better @namse ?

**Comment by namse** [comment]
Because there is one edge case for current pr. if user already opened browser, bundle server will serve previous build to them.

**Comment by bigfoodK** [comment]
Then I agree with the second idea.

**Comment by namse** [comment]
Let me do second solution later. I think it can be done next time. let's merge this pr first.

**Review by bigfoodK — APPROVED** [review]

**Pull request merged**
