### PR TITLE
Hide always-on cg parts on cg picker

### PR DESCRIPTION
**Pull request by bigfoodK**
### Before
image

### After
image

### CODE REVIEW

**Comment by namse** [comment]
@bigfoodK Please just hide always-on part on selection tab. it should be always on literally so don't have to show up to user in selection panel.

**Comment by bigfoodK** [comment]
> @bigfoodK Please just hide always-on part on selection tab. it should be always on literally so don't have to show up to user in selection panel.

That makes sense

**Comment by namse** [comment]
Please update title and demo on descriptions

**Comment by bigfoodK** [comment]
Title and description are updated

**Review by namse — APPROVED** [review]

**Pull request merged**
