### PR TITLE
Make namui-test-host rust version latest always

### PR DESCRIPTION
**Pull request by namse**

### CODE REVIEW

**Review by bigfoodK — APPROVED** [review]

**Comment by namse** [comment]
this test should fail before merging #260

**Comment by namse** [comment]
Wait. I think github action should run all test if docker image changed, but they didn't run.

image

**Comment by namse** [comment]
Please do not press `update branch` button. i'm testing that github aciton fail to build.

**Comment by namse** [comment]
post-test should be fail if any test job has been failed. Found bug.

**Comment by namse** [comment]
Fixed 
image

**Pull request merged**
